### ISSUE TITLE
Bot tries to execute join command without args if no channels specified.

### ISSUE THREAD

**Issue by pefoley2** [fwilson42/ununaffiliated#1]

**Comment by an-empty-string** [comment]
`chanregex` start characters should use `bot.server_supports['CHANTYPES']`.

**Comment by pefoley2** [comment]
Ok, the way I set it up was just validating that the initial configured channels are correct when running maketables. I don't think we have access to the server's config at that point.

**Comment by an-empty-string** [comment]
Oh, I see, nevermind.
